import UniGeo.Triangle.Thm01
import UniGeo.Triangle.Thm02
import UniGeo.Triangle.Thm03
import UniGeo.Triangle.Thm04
import UniGeo.Triangle.Thm05
import UniGeo.Triangle.Thm06
import UniGeo.Triangle.Thm07
import UniGeo.Triangle.Thm08
import UniGeo.Triangle.Thm09
import UniGeo.Triangle.Thm10
import UniGeo.Triangle.Thm11
import UniGeo.Triangle.Thm12
import UniGeo.Triangle.Thm13
import UniGeo.Triangle.Thm14
import UniGeo.Triangle.Thm15
import UniGeo.Triangle.Thm16
import UniGeo.Triangle.Thm17
import UniGeo.Triangle.Thm18
import UniGeo.Triangle.Thm19
import UniGeo.Triangle.Thm20
